---
- name: Delete VM Mass
  hosts: "{{XenMaster}}"
  vars_files: vars/{{tag}}_VM.json
  gather_facts: false
  become: true
  tasks:
    - name: Delete VM
      community.general.xenserver_guest:
        hostname: "{{ansible_host}}"
        username: "{{xenserver_username}}"
        password: "{{xenserver_password}}"
        uuid: "{{item.vm_uuid}}"
        state: absent
        force: true
      with_items: 
          - "{{vm}}"
