# Vars needed at runtime include: "tag" and "XenMaster" #
---
- name: Delete VM Mass
# This XenMaster variable is the pool master in your XCP-ng pool. You should define it with the exact name of the host in the XCP-ng Inventory #
  hosts: "{{XenMaster}}"
# This tag variable is the exact XOA tag of VMs you want to delete #  
  vars_files: vars/{{tag}}_VM.json
  gather_facts: false
  become: true
  tasks:
    - name: Delete VM
      community.general.xenserver_guest:
# This ansible_host variable is taken from the XenMaster host vars. The xenserver_username and xenserver_password variables are defined in the Ansible inventory for the XCP-ng devices #
        hostname: "{{ansible_host}}"
        username: "{{xenserver_username}}"
        password: "{{xenserver_password}}"
# This vm_uuid variable is defined in objects from the array called vm in the vars/{{tag}}_VM.json file #
        uuid: "{{item.vm_uuid}}"
        state: absent
        force: true
# This vm variable is the name of the array in the JSON file to loop against #
      with_items: 
          - "{{vm}}"
